." Manpage for the bin-tester
.TH bin-tester 1 "31 October 2019" "version 1.0"
.SH NAME
bin-tester - an automated testing tool that got out of hand
.SH SYNOPSIS
.B bin-solver
[-p <path>]
[--program <path>]
[-s <path>]
[--samples <path>]
[-m <value>]
[--max-time <value>]
[-d]
[--debug]
[-x]
[--extras]
[-c]
[--cpp]
[-j]
[--java]
[-2]
[--python2]
[-3]
[--python3]
[-h]
[--help]
.SH DESCRIPTION
.B bin-tester
is an automated testing tool made for a university project. This tester uses a samples directory which specifies input files with corresponding output files. The input files are written through
.B STDIN
to a
.B bin-solver
of choice. The
.B bin-solver
then produces an answer which is written to
.BR STDOUT , 
this answer is checked against the corresponding output file. If the answer is correct it will be shown as green if not then red. The
.B bin-tester
is also able to interrupt the
.B bin-solver
when it is taking to long for a certain case. You can furthermore show the
.B STDERR
output and the program has some primitive error detection for the
.BR bin-solver .
.SH OPTIONS
.TP
-p,--program <path>
Specify the path to your
.BR bin-solver .
.TP
-s,--samples <path>
Specify the path to your samples folder.
.TP
-m,--max-time <value>
Specify the max time your
.B bin-solver
is allowed to take to solve one sample. Use a optional suffix: 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days if you are a real enthusiast. A duration of 0 disables the timeout altogether. Note that only times under one minute are used in the computation of the statistics.
.TP
-d,--debug
Print everything your 
.B bin-solver
is writing to
.BR STDERR .
.TP
-x,--extras
Enable extra statistics, this is enabled by default. Note that the time shown at the end includes only correct answers.
.TP
-c,--cpp
Run a C++
.BR bin-solver .
.TP
-j,--java
Run a Java
.BR bin-solver .
.TP
-2,--python2
Run a python2
.BR bin-solver .
.TP
-3,--python3
Run a python3
.BR bin-solver .
.TP
-h,--help
Show this man page.
.SH REPORTING BUGS
Report issues or create pull request at GitHub:

https://github.com/Borroot/bin-tester/issues
.SH AUTHOR
Bram Pulles <borroot@live.nl>
.SH SEE ALSO
.BR bin-solver (1)

https://github.com/Borroot/bin-solver
