#!/usr/bin/env bash

# AUTHOR: Bram Pulles
# This program can be used to identify all the duplicate samples.

# I used it in particular to remove all the duplicates. It is easy
# to extend this program for other uses.

folder="${1:-../bin-samples}"
inputs=($(ls "$folder"/*.in))
count=0

for ((i = 0; i <= ${#inputs}; i++)) 
do
	for ((j = i+1; j <= ${#inputs}; j++))
	do
		if diff ${inputs[i]} ${inputs[j]} > /dev/null
		then
			let count++
			echo -e "${inputs[i]#*/}\t<->   ${inputs[j]#*/}" 
		fi
	done
done

echo "There are $count double(s)."
