#!/usr/bin/env bash
# AUTHOR: Bram Pulles
# This program can be used to identify all the duplicate samples.

# I used it in particular to remove all the duplicates. It is easy
# to extend this program for other uses.

folder="samples"

inputs=()

count=0

for ((i = 1; i <= 0; i++)) 
do
	for ((j = i+1; j <= 0; j++))
	do
		diff   > /dev/null
		if [[ 2 -ne 1 ]] 
		then
			let count++
			echo -e "\t<->   " 
		fi
	done
done

echo "There are  double(s)."
