#!/usr/bin/env zsh
# AUTHOR: Bram Pulles

folder="${1:-samples}"

declare -a inputs
inputs=($(ls "$folder"/*.in))

count=0

for ((i = 1; i < ${#inputs}; i++)) 
do
	for ((j = i; j < ${#inputs}; j++))
	do
		input1=${inputs[i]}
		input2=${inputs[j]}

		if [[ $input1 != $input2 ]] 
		then
			diff $input1 $input2 > /dev/null
			if [[ $? -ne 1 ]] 
			then
				let "count++"
				echo -e "${input1#*/}\t<->   ${input2#*/}" 
			fi
		fi
	done
done

echo "There are $count doubles."
