#!/usr/bin/env bash

# Check if the user is running on MacOS.
if [[ $(uname) == Darwin ]]
then 
	# Check if the person has brew.
	if brew -v
	then
		# Install getopt.
		if ! brew list gnu-getopt 2> /dev/null 
		then
			brew install gnu-getopt 
			echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile 
			export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
			brew link --force gnu-getopt
		fi

		# Install timeout.
		if ! brew list coreutils 2> /dev/null 
		then
			brew install coreutils 
			echo Now we will link 'gtimemout' to 'timeout' since this is the name in Linux.
			echo In order to do this you password will be asked.
			sudo ln -s /usr/local/bin/gtimeout /usr/local/bin/timeout
		fi
	else
		echo Please install brew.
	fi
fi
