#!/usr/bin/env bash

# Check if the user is running on MacOS.
if [[ $(uname) == Darwin ]]
then 
	# Check if the person has brew.
	if brew -v
	then
		# Install getopt.
		brew list gnu-getopt 2> /dev/null || (brew install gnu-getopt && echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && source ~/.bash_profile && brew link --force gnu-getopt) 

		# Install timeout.
		brew list coreutils  2> /dev/null || brew install coreutils && sudo ln -s /usr/local/bin/gtimeout /usr/local/bin/timeout
	else
		echo Please install brew.
	fi
fi
