#!/usr/bin/env zsh
# AUTHOR: Bram Pulles
# This program can be used to identify all the duplicate samples.

# I used it in particular to remove all the duplicates. It is easy
# to extend this program for other uses.

folder="${1:-samples}"

declare -a inputs
inputs=($(ls "$folder"/*.in))

count=0

for ((i = 1; i <= ${#inputs}; i++)) 
do
	for ((j = i; j <= ${#inputs}; j++))
	do
		input1=${inputs[i]}
		input2=${inputs[j]}

		if [[ $input1 != $input2 ]] 
		then
			diff $input1 $input2 > /dev/null
			if [[ $? -ne 1 ]] 
			then
				let "count++"
				echo -e "${input1#*/}\t<->   ${input2#*/}" 
			fi
		fi
	done
done

echo "There are $count double(s)."
